# Generated by Django 5.0.7 on 2024-08-13 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_post_followers_post_followings_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
