# Generated by Django 5.0.7 on 2024-08-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_user_joined_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="post",
            name="followings",
        ),
        migrations.AddField(
            model_name="user",
            name="fllwers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="flwings",
            field=models.IntegerField(default=0),
        ),
    ]
