# Generated by Django 5.0.7 on 2024-08-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_remove_post_followers_remove_post_followings_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="fllwers",
            new_name="flwers",
        ),
    ]
