# Generated by Django 5.0.7 on 2024-08-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_rename_fllwers_user_flwers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pts",
            field=models.IntegerField(default=0),
        ),
    ]
