# Generated by Django 5.0.7 on 2024-08-14 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_user_pts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likings",
                        to="network.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("liking", "liker")},
            },
        ),
    ]
